---
name: App-ZofCMS-Plugin-HTMLFactory-Entry
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to wrap content in three divs used for styling boxes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0108
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::HTMLFactory::Entry:
    file: lib/App/ZofCMS/Plugin/HTMLFactory/Entry.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
